Bump org.jetbrains.kotlin:kotlin-gradle-plugin from 1.9.0 to 1.9.10 (#4)
Bumps
[org.jetbrains.kotlin:kotlin-gradle-plugin](https://github.com/JetBrains/kotlin)
from 1.9.0 to 1.9.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">org.jetbrains.kotlin:kotlin-gradle-plugin's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.9.10</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60769"><code>KT-60769</code></a>
Partially revert KT-58371</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60659"><code>KT-60659</code></a>
Incorrect 'unresolved reference: addFirst' error with JDK 21</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60371"><code>KT-60371</code></a>
Native custom allocator link error</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60986"><code>KT-60986</code></a>
Native: static caches with custom runtime options are broken on
Linux</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60770"><code>KT-60770</code></a>
Fix false-positive ABSTRACT_MEMBER_NOT_IMPLEMENTED on toArray with JDK
21</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60231"><code>KT-60231</code></a>
NoClassDefFoundError: $$$$$NON_LOCAL_RETURN$$$$$ after upgrade to Kotlin
1.9.0</li>
</ul>
<h3>JavaScript</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60785"><code>KT-60785</code></a>
KJS: Destructured value class in suspend function fails with Uncaught
TypeError: can't convert to primitive type error</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60852"><code>KT-60852</code></a>
Kotlin JS(IR): IllegalArgumentException: Cross module dependency
resolution failed when updating to Kotlin 1.9.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57509"><code>KT-57509</code></a>
KJS: Compiler generates native JS operator == for comparing values with
Any type</li>
</ul>
<h3>Native</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60230"><code>KT-60230</code></a>
Native: &quot;unknown options: -ios_simulator_version_min
-sdk_version&quot; with Xcode 15 beta 3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60758"><code>KT-60758</code></a>
Native: Building for 'iOS-simulator', but linking in dylib built for
'iOS' in Xcode 15 beta 4</li>
</ul>
<h3>Native. C and ObjC Import</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-59167"><code>KT-59167</code></a>
Native: cinterop is unable to build interop libraries against the Xcode
15 Beta 1</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-61147"><code>KT-61147</code></a>
Kotlin Compiler 1.9.0 bundles a stripped unshadowed version of Gson</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60543"><code>KT-60543</code></a>
NoClassDefFoundError for com/gradle/scan/plugin/BuildScanExtension</li>
</ul>
<h2>Checksums</h2>
<table>
<thead>
<tr>
<th>File</th>
<th>Sha256</th>
</tr>
</thead>
<tbody>
<tr>
<td>kotlin-compiler-1.9.10.zip</td>

<td>7d74863deecf8e0f28ea54c3735feab003d0eac67e8d3a791254b16889c20342</td>
</tr>
<tr>
<td>kotlin-native-linux-x86_64-1.9.10.tar.gz</td>

<td>1db3679919f4449514e9d82451e7dfa73558ac9bc80b82579cd74d452c8faa5b</td>
</tr>
<tr>
<td>kotlin-native-macos-x86_64-1.9.10.tar.gz</td>

<td>f5650f2560438a692803d8fe07124529c19f1972f84fe09cfa2329b93f43828d</td>
</tr>
<tr>
<td>kotlin-native-macos-aarch64-1.9.10.tar.gz</td>

<td>d2cf5a484ac0808ab29fd3f6099df7c07330f81f3cbab949947e42e36138c3de</td>
</tr>
<tr>
<td>kotlin-native-windows-x86_64-1.9.10.zip</td>

<td>a34d56661455e94e1ba4dd09ec3c1adac6148fdedcf55eefb9a79c8ed01ff02c</td>
</tr>
</tbody>
</table>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/v1.9.10/ChangeLog.md">org.jetbrains.kotlin:kotlin-gradle-plugin's
changelog</a>.</em></p>
<blockquote>
<h2>1.9.10</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60769"><code>KT-60769</code></a>
Partially revert KT-58371</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60659"><code>KT-60659</code></a>
Incorrect 'unresolved reference: addFirst' error with JDK 21</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60371"><code>KT-60371</code></a>
Native custom allocator link error</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60986"><code>KT-60986</code></a>
Native: static caches with custom runtime options are broken on
Linux</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60770"><code>KT-60770</code></a>
Fix false-positive ABSTRACT_MEMBER_NOT_IMPLEMENTED on toArray with JDK
21</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60231"><code>KT-60231</code></a>
NoClassDefFoundError: $$$$$NON_LOCAL_RETURN$$$$$ after upgrade to Kotlin
1.9.0</li>
</ul>
<h3>JavaScript</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60785"><code>KT-60785</code></a>
KJS: Destructured value class in suspend function fails with Uncaught
TypeError: can't convert to primitive type error</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60852"><code>KT-60852</code></a>
Kotlin JS(IR): IllegalArgumentException: Cross module dependency
resolution failed when updating to Kotlin 1.9.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57509"><code>KT-57509</code></a>
KJS: Compiler generates native JS operator == for comparing values with
Any type</li>
</ul>
<h3>Native</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60230"><code>KT-60230</code></a>
Native: &quot;unknown options: -ios_simulator_version_min
-sdk_version&quot; with Xcode 15 beta 3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60758"><code>KT-60758</code></a>
Native: Building for 'iOS-simulator', but linking in dylib built for
'iOS' in Xcode 15 beta 4</li>
</ul>
<h3>Native. C and ObjC Import</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-59167"><code>KT-59167</code></a>
Native: cinterop is unable to build interop libraries against the Xcode
15 Beta 1</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-61147"><code>KT-61147</code></a>
Kotlin Compiler 1.9.0 bundles a stripped unshadowed version of Gson</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-60543"><code>KT-60543</code></a>
NoClassDefFoundError for com/gradle/scan/plugin/BuildScanExtension</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/3db61efe5e892bf27115f1ebcab957d903067ed4"><code>3db61ef</code></a>
[K/JS] Revert KT-60785 fix because the 1.9.0 contains old schema for
function...</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/3584af404640fddd5fb3cc9af0aaa894a69297d9"><code>3584af4</code></a>
Add ChangeLog for 1.9.10</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/7bab2dba1f1945438569e77715c4a4dec6db03f2"><code>7bab2db</code></a>
Remove gson from compiler fat jar</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/b925404e11f82dd263b7a6bf924dc84cd579e8fc"><code>b925404</code></a>
[K/JS] Fix autoboxing for inlined function ^KT-60785 Fixed</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/5801279810634ca3111ab46187a9de8e6a857cc4"><code>5801279</code></a>
[JS IR] De-optimize equality operator as workaround for KT-57509</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/79d3dda5ec881c1adee542c7e329ec15059e99bb"><code>79d3dda</code></a>
[K/N] Update osVersionMin for arm ios and tvos simulators</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/955598c9acc6aa9b039811d43cafdd5cbc1ea744"><code>955598c</code></a>
[K/N] Pick minimal iOS/tvOS depending on the Xcode version</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/b1aa582719c003b218652ee599c461aba0a3c97f"><code>b1aa582</code></a>
[K/N] Do not check caches consistency until all of them are built</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/0f6d84cca3ef69a5be4232a692d165327f975c01"><code>0f6d84c</code></a>
[K/N][tests] Added a reproducer for #KT-60371</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/d3b8607632b87aa7e9531c0637a34f437a25e306"><code>d3b8607</code></a>
[K/N][tests] Fixed CachesAutoBuildTest</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v1.9.0...v1.9.10">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin:kotlin-gradle-plugin&package-manager=gradle&previous-version=1.9.0&new-version=1.9.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>